name: clang-format
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jidicula/clang-format-action@v4.10.2
        with:
          clang-format-version: "15"
